"""Golden-fixture parity: the package pipeline must reproduce the
research pipeline (heartbeat) byte-for-byte on identical input bars.
Fixtures are generated by heartbeat/tools/export_s3_model.py — regenerate
them whenever either side changes, never hand-edit."""
import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from s3bounce.candles import DailyBar, DailyBarSeries  # noqa: E402
from s3bounce.features import compute_features, fresh_low_days  # noqa: E402
from s3bounce.model import load_artifact, score  # noqa: E402
from s3bounce.setups import causal_setups  # noqa: E402

FIXTURES = Path(__file__).parent / "fixtures"
PAIRS = ("BTC_USD", "ETH_USD", "ZEC_USD")


def load(pair):
    return json.loads((FIXTURES / f"parity_{pair}.json").read_text())


def bars_of(fix):
    return [DailyBar(open_ts=float(b["ts"]), open=b["open"], high=b["high"],
                     low=b["low"], close=b["close"], volume=b["volume"])
            for b in fix["bars"]]


@pytest.fixture(scope="module")
def fixtures():
    return {p: load(p) for p in PAIRS}


@pytest.fixture(scope="module")
def low_days(fixtures):
    return {p.replace("_", "/"): fresh_low_days(bars_of(f))
            for p, f in fixtures.items()}


@pytest.mark.parametrize("pair", PAIRS)
def test_hourly_aggregation_matches_research_resample(fixtures, pair):
    fix = fixtures[pair]
    series = DailyBarSeries()
    for r in fix["hourly_sample"]:
        series.update_1h(r["ts"], r["open"], r["high"], r["low"],
                         r["close"], r["volume"])
    got = {b.day: b for b in series.completed_bars(now_ts=2**40)}
    checked = 0
    for rb in fix["bars"]:
        day = rb["ts"] // 86400
        if day not in got:
            continue
        g = got[day]
        for field in ("open", "high", "low", "close", "volume"):
            assert abs(getattr(g, field) - rb[field]) < 1e-9, \
                f"{pair} day {day} field {field}"
        checked += 1
    assert checked >= 25, f"only {checked} overlapping days verified"


@pytest.mark.parametrize("pair", PAIRS)
def test_setups_features_scores_parity(fixtures, low_days, pair):
    fix = fixtures[pair]
    bars = bars_of(fix)
    setups = causal_setups(bars)
    assert len(setups) == len(fix["setups"]), \
        f"{pair}: {len(setups)} setups vs research {len(fix['setups'])}"
    compute_features(bars, setups, low_days)
    art = load_artifact()
    model = art.models.get(pair.replace("_", "/"))
    for got, ref in zip(setups, fix["setups"]):
        assert got.low_idx == ref["low_idx"]
        assert abs(got.low_px - ref["low_px"]) < 1e-12
        assert abs(got.atr - ref["atr"]) < 1e-9
        assert got.bounce_idx == ref["bounce_idx"]
        assert got.label == ref["label"]
        for f, v in ref["x"].items():
            assert abs(got.x[f] - v) < 1e-9, f"{pair} {f}"
        assert got.resolve_ts == ref["resolve_ts"] or \
            (got.resolve_ts is not None and ref["resolve_ts"] is not None
             and abs(got.resolve_ts - ref["resolve_ts"]) < 1e-6)
        if model is not None:
            key = f"{ref['low_idx']}@{ref['low_px']:.10g}"
            assert abs(score(model, got.x) - fix["scores"][key]) < 1e-9
    if pair == "ZEC_USD":
        assert model is None                      # structurally untradable
