#!/usr/bin/env python3
"""Deterministic watermark gate for review and merge-to-main.

Pinned copy of ~/.grok/skills/remove-ai-marks/scripts/check.py (keep in
sync when the gate regexes change). CI job name: Watermark Gate.

Certificates only: Layer A Unicode + agent trailers/banners (+ optional
watermarks-remover inspect when WATERMARKS_SCRIPTS is set). Never Layer B.
Never claims official-detector failure.

Exit 0 = no actionable deterministic findings
Exit 1 = findings (block merge / fail CI)
Exit 2 = usage / git error
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

TRAILER_RE = re.compile(
    r"^[ \t]*(?:Co-Authored-By|Co-authored-by):\s*.*(?:"
    r"noreply@anthropic\.com|"
    r"claude(?:\s|$)|"
    r"cursoragent@cursor\.com|"
    r"@cursor\.com|"
    r"copilot@github\.com|"
    r"Copilot\[bot\]|"
    r"codex@openai\.com|"
    r"noreply@openai\.com|"
    r"@users\.noreply\.github\.com"
    r").*$",
    re.IGNORECASE | re.MULTILINE,
)
BANNER_RE = re.compile(
    r"^[ \t]*(?:#|//|--|/\*|\*|<!--)?[ \t]*"
    r"(?:(?:🤖\s*)?Generated with (?:\[)?Claude Code|"
    r"Generated by Claude|"
    r"Claude-Session:\s*https?://)",
    re.IGNORECASE | re.MULTILINE,
)

# Actionable carriers only. Exotic spaces stay informational (not a merge fail).
ZW_FAMILY = {0x200B, 0x200C, 0x200D, 0x2060, 0xFEFF}
BIDI = set(range(0x202A, 0x202F)) | set(range(0x2066, 0x206A))
TAGS = {0xE0001} | set(range(0xE0020, 0xE007F))
SOFT_HYPHEN = {0x00AD}

SKIP_DIR_PARTS = {
    ".git",
    "node_modules",
    "__pycache__",
    ".venv",
    "venv",
    "dist",
    "build",
    ".next",
    "target",
    "fixtures",
    ".wm-tmp",
    ".pytest_cache",
}
SKIP_NAMES = {
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "go.sum",
    "cargo.lock",
}
SKIP_SUFFIXES = {
    ".png",
    ".jpg",
    ".jpeg",
    ".webp",
    ".gif",
    ".bmp",
    ".tiff",
    ".tif",
    ".avif",
    ".heic",
    ".heif",
    ".pdf",
    ".docx",
    ".xlsx",
    ".pptx",
    ".odt",
    ".epub",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".ico",
    ".mp4",
    ".zip",
    ".pyc",
    ".exe",
    ".dll",
    ".so",
    ".min.js",
    ".map",
}
TEXT_READ_CAP = 2_000_000


def _is_emoji_cp(cp: int) -> bool:
    return (0x1F300 <= cp <= 0x1FAFF) or (0x2600 <= cp <= 0x27BF) or (0xFE00 <= cp <= 0xFE0F)


def skip_path(path: Path) -> bool:
    parts = {p.lower() for p in path.parts}
    if parts & SKIP_DIR_PARTS:
        return True
    if path.name.lower() in SKIP_NAMES:
        return True
    suf = "".join(path.suffixes).lower()
    if path.suffix.lower() in SKIP_SUFFIXES or suf.endswith(".min.js"):
        return True
    return False


def scan_text(text: str) -> list[dict]:
    hits: list[dict] = []
    n_trailer = len(TRAILER_RE.findall(text))
    if n_trailer:
        hits.append({"channel": "deterministic", "kind": "trailer", "count": n_trailer})
    n_banner = len(BANNER_RE.findall(text))
    if n_banner:
        hits.append({"channel": "deterministic", "kind": "banner", "count": n_banner})

    cps = [ord(ch) for ch in text]
    counts: dict[str, int] = {}
    for i, cp in enumerate(cps):
        if cp == 0xFEFF and i == 0:
            continue
        if cp == 0x200D:
            prev = cps[i - 1] if i else 0
            nxt = cps[i + 1] if i + 1 < len(cps) else 0
            if _is_emoji_cp(prev) or _is_emoji_cp(nxt):
                continue
        label = None
        if cp in ZW_FAMILY:
            label = "zwj_family"
        elif cp in BIDI:
            label = "bidi"
        elif cp in TAGS:
            label = "tag_chars"
        elif cp in SOFT_HYPHEN:
            label = "strip"
        if label:
            counts[label] = counts.get(label, 0) + 1
    for kind, count in sorted(counts.items()):
        hits.append({"channel": "deterministic", "kind": kind, "count": count})
    return hits


def git_changed(base: str, include_untracked: bool) -> list[Path]:
    try:
        out = subprocess.check_output(
            ["git", "-c", "core.quotepath=false", "diff", "--name-only", "--diff-filter=ACMRTUXB", base],
            text=True,
            stderr=subprocess.DEVNULL,
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"git diff failed vs {base}: {e}", file=sys.stderr)
        raise SystemExit(2)
    names = [ln.strip() for ln in out.splitlines() if ln.strip()]
    if include_untracked:
        try:
            extra = subprocess.check_output(
                ["git", "-c", "core.quotepath=false", "ls-files", "--others", "--exclude-standard"],
                text=True,
                stderr=subprocess.DEVNULL,
            )
            names.extend(ln.strip() for ln in extra.splitlines() if ln.strip())
        except subprocess.CalledProcessError:
            pass
    root = Path(subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip())
    return [root / n for n in dict.fromkeys(names)]


def wm_inspect(path: Path, scripts: Path) -> list[dict]:
    inspect = scripts / "inspect_file.py"
    if not inspect.is_file():
        return []
    try:
        proc = subprocess.run(
            [sys.executable, str(inspect), "--json", str(path)],
            capture_output=True,
            text=True,
            timeout=20,
        )
    except (OSError, subprocess.TimeoutExpired):
        return []
    if not proc.stdout.strip():
        return []
    try:
        data = json.loads(proc.stdout)
    except json.JSONDecodeError:
        return []
    extra: list[dict] = []
    if data.get("c2pa") or (isinstance(data.get("report"), dict) and data["report"].get("c2pa")):
        extra.append({"channel": "c2pa", "kind": "c2pa", "count": 1})
    return extra


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--base", default="", help="git ref to diff against (default: origin/main)")
    p.add_argument("--files", nargs="*", default=[], help="explicit file list (skips git)")
    p.add_argument("--all", action="store_true", help="scan cwd recursively (not just the diff)")
    p.add_argument("--include-untracked", action="store_true")
    p.add_argument("--json", action="store_true")
    args = p.parse_args()

    if args.files:
        paths = [Path(f) for f in args.files]
    elif args.all:
        cwd = Path.cwd()
        paths = [p for p in cwd.rglob("*") if p.is_file()]
    else:
        base = args.base or os.environ.get("WATERMARK_GATE_BASE") or "origin/main"
        paths = git_changed(base, args.include_untracked)

    wm = os.environ.get("WATERMARKS_SCRIPTS", "")
    wm_scripts = Path(wm) if wm else None

    findings: list[dict] = []
    scanned = 0
    enforce_dir_skip = not args.files
    for path in paths:
        if not path.is_file():
            continue
        if enforce_dir_skip and skip_path(path):
            continue
        if path.name.lower() in SKIP_NAMES:
            continue
        scanned += 1
        try:
            raw = path.read_bytes()[:TEXT_READ_CAP]
            text = raw.decode("utf-8", errors="replace")
        except OSError as e:
            findings.append({"path": str(path), "hits": [{"kind": "io", "error": str(e)}]})
            continue
        hits = scan_text(text)
        if wm_scripts and path.suffix.lower() in {".png", ".jpg", ".jpeg", ".webp", ".svg"}:
            hits.extend(wm_inspect(path, wm_scripts))
        if hits:
            findings.append({"path": str(path), "hits": hits})

    report = {
        "ok": not findings,
        "scanned": scanned,
        "findings": findings,
        "official": "unavailable",
        "honesty": [
            "official text detector: unavailable",
            "deterministic only (unicode / trailer / banner); not a watermark score",
            "this run does not prove the official Claude text detector will fail",
            "this run does not prove the text is human-written",
            "absence of a mark does not prove Claude was uninvolved",
        ],
    }
    if args.json or not sys.stdout.isatty():
        print(json.dumps(report, indent=2))
    else:
        print(f"watermark-gate scanned={scanned} findings={len(findings)}")
        for item in findings:
            kinds = ", ".join(f"{h.get('kind')}={h.get('count', 1)}" for h in item["hits"])
            print(f"  {item['path']}: {kinds}")
        if not findings:
            print("deterministic: absent")
    return 1 if findings else 0


if __name__ == "__main__":
    raise SystemExit(main())
