#!/usr/bin/env python3
"""Range fidelity gate for regime-selective rails vs AI-control study.

Study anchors (causal next-bar, SOL/USD 1h, realistic fills, competition):
  90d  selective ≈ −1.27%   baseline ≈ −13.21%
  365d selective ≈ −6.78%   baseline ≈ −14.26%

Bands (design / plan — not absolute +P&L claims):
  sol_90d  selective_ret ∈ [-4.3, +1.7],  edge vs base ≥ +5 pp
  sol_365d selective_ret ∈ [-10.8, -2.8], edge vs base ≥ +5 pp

Usage:
  python tools/retest_regime_selective_ranges.py
  python tools/retest_regime_selective_ranges.py --db hydra_history.sqlite
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tools"))

from ai_control_counterfactual import (  # noqa: E402
    POLICIES,
    buy_and_hold,
    load_candles,
    run_policy,
)
import sqlite3  # noqa: E402

BANDS = {
    "sol_90d": {
        "days": 90,
        "selective_ret": (-4.3, 1.7),
        "min_edge_vs_base_pp": 5.0,
        "study_selective": -1.27,
        "study_baseline": -13.21,
    },
    "sol_365d": {
        "days": 365,
        "selective_ret": (-10.8, -2.8),
        "min_edge_vs_base_pp": 5.0,
        "study_selective": -6.78,
        "study_baseline": -14.26,
    },
}


def _window(db: str, pair: str, grain: int, days: int):
    con = sqlite3.connect(db)
    row = con.execute(
        "SELECT MIN(ts), MAX(ts), COUNT(*) FROM ohlc WHERE pair=? AND grain_sec=?",
        (pair, grain),
    ).fetchone()
    con.close()
    tmin, tmax, n = row
    t0 = max(float(tmin), float(tmax) - days * 86400)
    candles = load_candles(db, pair, grain, t0, float(tmax))
    return candles


def main() -> int:
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=str(ROOT / "hydra_history.sqlite"))
    ap.add_argument(
        "--out",
        default=str(ROOT / ".hydra-research" / "regime_selective_fidelity_report.md"),
    )
    args = ap.parse_args()

    pair = "SOL/USD"
    grain = 3600
    rows = []
    failures = []

    print("Regime-selective range fidelity retest (no lookahead)")
    print(f"db={args.db} pair={pair} grain={grain}s fill=realistic\n")

    for name, band in BANDS.items():
        candles = _window(args.db, pair, grain, band["days"])
        bh = buy_and_hold(candles, 100.0)
        base = run_policy(
            candles, "baseline", POLICIES["baseline"],
            initial=100.0, fill_model="realistic", mode="competition",
            regime_selective=False,
        )
        sel = run_policy(
            candles, "ai_proxy_selective", POLICIES["ai_proxy_selective"],
            initial=100.0, fill_model="realistic", mode="competition",
            regime_selective=True,
        )
        edge = sel["return_pct"] - base["return_pct"]
        lo, hi = band["selective_ret"]
        in_band = lo <= sel["return_pct"] <= hi
        edge_ok = edge >= band["min_edge_vs_base_pp"]
        ok = in_band and edge_ok
        if not ok:
            failures.append(name)

        row = {
            "window": name,
            "n": len(candles),
            "bh_pct": bh["return_pct"],
            "baseline_pct": base["return_pct"],
            "selective_pct": sel["return_pct"],
            "edge_pp": edge,
            "baseline_fills": base["fills"],
            "selective_fills": sel["fills"],
            "study_selective": band["study_selective"],
            "study_baseline": band["study_baseline"],
            "band": band["selective_ret"],
            "in_band": in_band,
            "edge_ok": edge_ok,
            "pass": ok,
        }
        rows.append(row)
        status = "PASS" if ok else "FAIL"
        print(
            f"  [{status}] {name}: sel={sel['return_pct']:+.2f}% "
            f"(band {lo}..{hi}, study {band['study_selective']:+.2f}) "
            f"base={base['return_pct']:+.2f}% edge={edge:+.2f}pp "
            f"fills sel/base={sel['fills']}/{base['fills']}"
        )

    # Faithfulness checklist
    checks = [
        ("Re-regulation not deregulation (selective uses engine rails)", True),
        ("Selective fewer fills than baseline (both windows)",
         all(r["selective_fills"] < r["baseline_fills"] for r in rows)),
        ("Selective edge ≥ +5pp both windows", all(r["edge_ok"] for r in rows)),
        ("Selective return in study bands", all(r["in_band"] for r in rows)),
        ("Absolute +P&L not required / not claimed", True),
    ]

    report_lines = [
        "# Regime-selective fidelity report",
        "",
        "Generated by `tools/retest_regime_selective_ranges.py`.",
        "Causal next-bar fills only; no LLM; engine `regime_selective=True`.",
        "",
        "## Results",
        "",
        "| Window | Baseline % | Selective % | Study sel % | Edge pp | Fills s/b | Band | Pass |",
        "|--------|------------|-------------|-------------|---------|-----------|------|------|",
    ]
    for r in rows:
        report_lines.append(
            f"| {r['window']} | {r['baseline_pct']:+.2f} | {r['selective_pct']:+.2f} | "
            f"{r['study_selective']:+.2f} | {r['edge_pp']:+.2f} | "
            f"{r['selective_fills']}/{r['baseline_fills']} | {r['band']} | "
            f"{'YES' if r['pass'] else 'NO'} |"
        )
    report_lines.extend(["", "## Faithfulness checklist", ""])
    for label, ok in checks:
        report_lines.append(f"- [{'x' if ok else ' '}] {label}")
    report_lines.extend([
        "",
        "## Verdict",
        "",
        ("**PASS** — selective rails reproduce study ranges."
         if not failures else
         f"**FAIL** — windows out of band: {', '.join(failures)}"),
        "",
        "Note: positive absolute P&L is **not** claimed on these windows.",
        "",
    ])
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(report_lines), encoding="utf-8")
    print(f"\nWrote {out_path}")

    if failures:
        print("FAIL fidelity bands")
        return 1
    if not all(c[1] for c in checks):
        print("FAIL faithfulness checklist")
        return 1
    print("PASS all fidelity bands + checklist")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
